kind: pipeline
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test ./... -v

- name: fetch
  image: docker:git
  commands:
    - git fetch --tags
  when:
    event: tag

- name: release
  image: golang
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes:
    - name: deps
      path: /go
  commands:
    - go mod download
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag

volumes:
- name: deps
  temp: {}
